=== Bqhuy2312/KTPM2211073_BuiQuangHuy_XML/donhang.dtd
<!ELEMENT donhangs (order:donhang*)>
<!ATTLIST donhangs
    xmlns:order CDATA #FIXED "http://company.com/order"
    xmlns:prod CDATA #FIXED "http://company.com/product"
>

<!ELEMENT order:donhang (order:sanpham_list)>
<!ATTLIST order:donhang
    id ID #REQUIRED
    customer CDATA #REQUIRED
    date CDATA #REQUIRED
>

<!ELEMENT order:sanpham_list (prod:sanpham*)>
<!ELEMENT prod:sanpham EMPTY>
<!ATTLIST prod:sanpham
    id ID #REQUIRED
    quantity CDATA #REQUIRED
    price CDATA #REQUIRED
>

=== Bqhuy2312/KTPM2211073_BuiQuangHuy_XML/donhang.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE donhangs SYSTEM "donhang.dtd">
<donhangs xmlns:order="http://company.com/order" xmlns:prod="http://company.com/product">

    <order:donhang id="DH001" customer="Nguyễn Văn A" date="2025-09-15">
        <order:sanpham_list>
            <prod:sanpham id="SP001" quantity="2" price="15000000" />
            <prod:sanpham id="SP002" quantity="1" price="1200000" />
        </order:sanpham_list>
    </order:donhang>

    <order:donhang id="DH002" customer="Trần Thị B" date="2025-09-16">
        <order:sanpham_list>
            <prod:sanpham id="SP003" quantity="3" price="500000" />
            <prod:sanpham id="SP004" quantity="5" price="250000" />
        </order:sanpham_list>
    </order:donhang>

</donhangs>
