=== Bqhuy2312/KTPM2211073_BuiQuangHuy_XML/nhansu.dtd
<!ELEMENT congty (dep:phongban*)>
<!ATTLIST congty
    xmlns:hr CDATA #FIXED "http://company.com/hr"
    xmlns:dep CDATA #FIXED "http://company.com/department"
>

<!ELEMENT dep:phongban (hr:nhanvien*)>
<!ATTLIST dep:phongban
    name CDATA #REQUIRED
>

<!ELEMENT hr:nhanvien (hr:id, hr:name, hr:position)>

<!ELEMENT hr:id (#PCDATA)>
<!ELEMENT hr:name (#PCDATA)>
<!ELEMENT hr:position (#PCDATA)>

=== Bqhuy2312/KTPM2211073_BuiQuangHuy_XML/nhansu.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE congty SYSTEM "nhansu.dtd">
<congty xmlns:hr="http://company.com/hr" xmlns:dep="http://company.com/department">

    <dep:phongban name="Phòng Kế Toán">
        <hr:nhanvien>
            <hr:id>NV001</hr:id>
            <hr:name>Nguyễn Văn A</hr:name>
            <hr:position>Kế toán trưởng</hr:position>
        </hr:nhanvien>
        <hr:nhanvien>
            <hr:id>NV002</hr:id>
            <hr:name>Trần Thị B</hr:name>
            <hr:position>Kế toán viên</hr:position>
        </hr:nhanvien>
    </dep:phongban>

    <dep:phongban name="Phòng CNTT">
        <hr:nhanvien>
            <hr:id>NV003</hr:id>
            <hr:name>Lê Văn C</hr:name>
            <hr:position>Lập trình viên</hr:position>
        </hr:nhanvien>
    </dep:phongban>

</congty>
